//  Triangular, pentagonal, and hexagonal
/*	Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n-1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal. 
Pergjigja e sakte eshte: 1533776805  */

#include<iostream>
#include<ctime>

using namespace std;

bool IsTriangleNum(unsigned long long int a);

bool isPentagonalNum(unsigned long long int a);

int main()
{
	bool found = false;
	int n = 144;
	int testNumber;
	while (!found)
	{
		testNumber = n * ((2 * n) - 1);
		if (IsTriangleNum(2 * testNumber) && isPentagonalNum(2 * testNumber))
		{
			found = true;
		}
		n++;
	}
	cout << testNumber << endl;
	cout << endl << clock() << endl;
	system("pause");
	return 0;
}

bool IsTriangleNum(unsigned long long int a)
{
	int n = 286;
	unsigned long long int num = 0;
	while (num < a)
	{
		num = n * (n + 1);
		if (num == a)
		{
			return true;
		}
		else
		{
			n++;
		}
	}
	return false;
}

bool isPentagonalNum(unsigned long long int a)
{
	int n = 166;
	unsigned long long int num = 0;
	while (num < a)
	{
		num = n * ((3 * n) - 1);
		if (num == a)
		{
			return true;
		}
		else
		{
			n++;
		}
	}
	return false;
}
